### ISSUE TITLE
 PlatformException

### ISSUE THREAD

**Issue by ChuanqingYang** [basnetjiten/flutter_gcaptcha_v3#1]
After started the local server i got errors below:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1010:7)
<asynchronous suspension>
#1      WebKitWebViewPlatformController.runJavascript (package:webview_flutter_wkwebview/src/web_kit_webview_widget.dart:349:7)
<asynchronous suspension>

**Comment by basnetjiten** [comment]
@ChuanqingYang I have updated the package now. This should be resolved. 
PS: Don't forget to host index.html with real domain urls.
