### ISSUE TITLE
 PlatformException

### ISSUE THREAD

**Issue by jalal-zy** [basnetjiten/flutter_gcaptcha_v3#10]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: executeCaptcha, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 15}), null)
<img width="1275" alt="Screenshot 2024-07-01 at 10 22 01 AM" src="https://github.com/basnetjiten/flutter_gcaptcha_v3/assets/94610794/bc502806-cabf-43d5-bfb9-fe4090b75021">

If I removed the webview 
I get an error:
LateInitializationError: Field 'controller' has not been initialized.

**Comment by yassine-bennkhay** [comment]
I am on this `LateInitializationError: Field 'controller' has not been initialized` error 2 days now, have you found any solution?

**Comment by basnetjiten** [comment]
Hi @yassine-bennkhay @jalal-zy , Please make sure the RecaptchWebview is rendered before using executeV3 method call. Webview usually takes 3 second to initialize and hence the instance of controller will be available after 3 seconds

**Comment by basnetjiten** [comment]
@jalal-zy You should not remove RecaptchaWebview. It is required to use executeV3 method call. You should not use in the splash screen or remove it using any navigation calls. It should be fully presented in the pages , for example you can use it on login or registration pages
