### ISSUE TITLE
setup is not clear enoigh i get lateinitialization error

### ISSUE THREAD

**Issue by shahindadashov** [basnetjiten/flutter_gcaptcha_v3#11]
LateError (LateInitializationError: Field 'controller' has not been initialized.)

#0      RecaptchaHandler.controller (package:flutter_gcaptcha_v3/recaptca_config.dart)
#1      RecaptchaHandler.executeV3 (package:flutter_gcaptcha_v3/recaptca_config.dart:45:16)

**Comment by BhupinderRana** [comment]
hi @shahindadashov you find any solution ?

**Comment by basnetjiten** [comment]
Hi @BhupinderRana @shahindadashov This should be resolved in the new version. Please let me know if the issue persists. Thanks
