### ISSUE TITLE
run javascript error

### ISSUE THREAD

**Issue by sokary03** [basnetjiten/flutter_gcaptcha_v3#17]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: readyCaptcha, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 13}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1167:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:462:7)
<asynchronous suspension>

I followed the instructions , i have put the html file in our domain and provided the correct url path 
why is this error appearing ?

**Comment by basnetjiten** [comment]
Hi @sokary03 , could you please check and try running the default project in the example directory? Does it work as expected for you?
