### ISSUE TITLE
Implement Direct Asynchronous Function for Token Retrieval

### ISSUE THREAD

**Issue by MerNat** [basnetjiten/flutter_gcaptcha_v3#6]
The current mechanism for retrieving the reCAPTCHA token relies on the `onTokenReceived` callback. A direct asynchronous method would simplify the process and align with common Flutter asynchronous patterns.

**Suggested Implementation:**
Introduce a new method, e.g., `Future<String> getToken()`, that returns a `Future` of the token. This method can internally handle the execution of the reCAPTCHA and resolve the `Future` once the token is received.

**Comment by basnetjiten** [comment]
Hi @MerNat thanks for the feedback, As an alternative now the new version supports a getter to access the captcha token.

**Comment by MerNat** [comment]
> Hi @MerNat thanks for the feedback, As an alternative now the new version supports a getter to access the captcha token.

Thank you @basnetjiten
