### ISSUE TITLE
Error: Uncaught ReferenceError: readyCaptcha is not defined

### ISSUE THREAD

**Issue by tntkhang** [basnetjiten/flutter_gcaptcha_v3#7]
I follow all the instroduction, upload the index.html to our hosting but and also register the V3 recaptcha but when run the app it show error:

I/chromium(21519): [INFO:CONSOLE(1)] "Uncaught ReferenceError: readyCaptcha is not defined", source: https://khangtran-development.web.app/index.html (1)

Seem that the function readyCaptcha on the javascript does not loaded.

**Comment by g-30** [comment]
@basnetjiten I encountered the same issue. It looks like readyCaptcha function is called before the page finishes loading.

**Comment by ortemmetro** [comment]
How did you fixed this issue?

**Comment by db-assistant** [comment]
HI, @basnetjiten  COULD YOU PLEASE TELL USE HOW TO FIX THIS ISSUE?

**Comment by basnetjiten** [comment]
Hi @oktopidengbo , This issue should be resolved in the new version now. Please check the updated index.html as well as shown in the example app.
