### ISSUE TITLE
PlatformException(error, java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.

### ISSUE THREAD

**Issue by pushkar2113** [basnetjiten/flutter_gcaptcha_v3#8]
I'm getting issues the above issues.

I added the ReCaptchaWebView in login Screen so that I can implement recaptcha on login api which sends otp.

Now next screen is OTP screen there we have option for resend otp, So I need to use ReCaptchaWebView there also.
But when I'm doing so I'm getting the below excception:

The Android view returned from PlatformView#getView() was already added to a parent view.

Please help me out in fixing this.

**Comment by basnetjiten** [comment]
Hi @pushkar2113 It should be resolved in the new version flutter_gcaptcha_v3: 1.2.0
